# Generated by Django 4.0.3 on 2022-03-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='teams/', verbose_name='image')),
                ('desc', models.TextField(verbose_name='description')),
                ('job', models.CharField(max_length=50, verbose_name='job')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='product/', verbose_name='image')),
                ('price', models.FloatField(verbose_name='price')),
                ('discount_price', models.FloatField(verbose_name='discount price')),
                ('discount_perc', models.IntegerField(verbose_name='discount perc')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('rated_people_num', models.IntegerField(verbose_name='people rating number ')),
                ('sold_num', models.IntegerField(verbose_name='sold quqntity number ')),
                ('description', models.TextField(verbose_name='description')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('avail_check', models.BooleanField(default=True, verbose_name='avail  checking ')),
                ('avail_num', models.IntegerField(verbose_name='avail number')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
