# Generated by Django 4.0.3 on 2022-03-25 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 12, 12, 37, 823424, tzinfo=utc), verbose_name='created at'),
        ),
    ]
